
version: '3'
services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - drill
      - mysql
  drill:
    image: apache/drill
    ports:
      - "8047:8047"
    command: ["drill-embedded"]
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: etl_db
    ports:
      - "3306:3306"
